package com.zdd.risk.bean;

import java.util.Date;

public class ApplyAmount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.id
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.bizNo
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String bizNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.userId
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.modelNo
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String modelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.applyAmount
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private Integer applyAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.applyDays
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String applyDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.applyMonths
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String applyMonths;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.contractAmount
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private Integer contractAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.createTime
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.applyId
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.updateTime
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.realName
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.idCard
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.bankCard
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String bankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.bankName
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyamount.bankMobile
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    private String bankMobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.id
     *
     * @return the value of risk_applyamount.id
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.id
     *
     * @param id the value for risk_applyamount.id
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.bizNo
     *
     * @return the value of risk_applyamount.bizNo
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.bizNo
     *
     * @param bizNo the value for risk_applyamount.bizNo
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.userId
     *
     * @return the value of risk_applyamount.userId
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.userId
     *
     * @param userId the value for risk_applyamount.userId
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.modelNo
     *
     * @return the value of risk_applyamount.modelNo
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.modelNo
     *
     * @param modelNo the value for risk_applyamount.modelNo
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo == null ? null : modelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.applyAmount
     *
     * @return the value of risk_applyamount.applyAmount
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public Integer getApplyAmount() {
        return applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.applyAmount
     *
     * @param applyAmount the value for risk_applyamount.applyAmount
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setApplyAmount(Integer applyAmount) {
        this.applyAmount = applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.applyDays
     *
     * @return the value of risk_applyamount.applyDays
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getApplyDays() {
        return applyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.applyDays
     *
     * @param applyDays the value for risk_applyamount.applyDays
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setApplyDays(String applyDays) {
        this.applyDays = applyDays == null ? null : applyDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.applyMonths
     *
     * @return the value of risk_applyamount.applyMonths
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getApplyMonths() {
        return applyMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.applyMonths
     *
     * @param applyMonths the value for risk_applyamount.applyMonths
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setApplyMonths(String applyMonths) {
        this.applyMonths = applyMonths == null ? null : applyMonths.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.contractAmount
     *
     * @return the value of risk_applyamount.contractAmount
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public Integer getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.contractAmount
     *
     * @param contractAmount the value for risk_applyamount.contractAmount
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setContractAmount(Integer contractAmount) {
        this.contractAmount = contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.createTime
     *
     * @return the value of risk_applyamount.createTime
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.createTime
     *
     * @param createTime the value for risk_applyamount.createTime
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.applyId
     *
     * @return the value of risk_applyamount.applyId
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.applyId
     *
     * @param applyId the value for risk_applyamount.applyId
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.updateTime
     *
     * @return the value of risk_applyamount.updateTime
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.updateTime
     *
     * @param updateTime the value for risk_applyamount.updateTime
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.realName
     *
     * @return the value of risk_applyamount.realName
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.realName
     *
     * @param realName the value for risk_applyamount.realName
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.idCard
     *
     * @return the value of risk_applyamount.idCard
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.idCard
     *
     * @param idCard the value for risk_applyamount.idCard
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.bankCard
     *
     * @return the value of risk_applyamount.bankCard
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.bankCard
     *
     * @param bankCard the value for risk_applyamount.bankCard
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.bankName
     *
     * @return the value of risk_applyamount.bankName
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.bankName
     *
     * @param bankName the value for risk_applyamount.bankName
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyamount.bankMobile
     *
     * @return the value of risk_applyamount.bankMobile
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public String getBankMobile() {
        return bankMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyamount.bankMobile
     *
     * @param bankMobile the value for risk_applyamount.bankMobile
     *
     * @mbg.generated Fri Nov 23 15:15:00 CST 2018
     */
    public void setBankMobile(String bankMobile) {
        this.bankMobile = bankMobile == null ? null : bankMobile.trim();
    }
}