package com.zdd.risk.bean;

import java.util.Date;

public class ApproveStrategyResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.id
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.userId
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.bizNo
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String bizNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.applyId
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.mobileAuthentication
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String mobileAuthentication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.virtualTip
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String virtualTip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.mobileOnlineTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String mobileOnlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.loanBlackList
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String loanBlackList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.remark
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.createTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.updateTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.zrobotCredit
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String zrobotCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.zrobotBlack
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String zrobotBlack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.financalBehavior
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String financalBehavior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approvestrategyresult.antiFraud
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    private String antiFraud;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.id
     *
     * @return the value of risk_approvestrategyresult.id
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.id
     *
     * @param id the value for risk_approvestrategyresult.id
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.userId
     *
     * @return the value of risk_approvestrategyresult.userId
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.userId
     *
     * @param userId the value for risk_approvestrategyresult.userId
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.bizNo
     *
     * @return the value of risk_approvestrategyresult.bizNo
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.bizNo
     *
     * @param bizNo the value for risk_approvestrategyresult.bizNo
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.applyId
     *
     * @return the value of risk_approvestrategyresult.applyId
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.applyId
     *
     * @param applyId the value for risk_approvestrategyresult.applyId
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.mobileAuthentication
     *
     * @return the value of risk_approvestrategyresult.mobileAuthentication
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getMobileAuthentication() {
        return mobileAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.mobileAuthentication
     *
     * @param mobileAuthentication the value for risk_approvestrategyresult.mobileAuthentication
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setMobileAuthentication(String mobileAuthentication) {
        this.mobileAuthentication = mobileAuthentication == null ? null : mobileAuthentication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.virtualTip
     *
     * @return the value of risk_approvestrategyresult.virtualTip
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getVirtualTip() {
        return virtualTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.virtualTip
     *
     * @param virtualTip the value for risk_approvestrategyresult.virtualTip
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setVirtualTip(String virtualTip) {
        this.virtualTip = virtualTip == null ? null : virtualTip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.mobileOnlineTime
     *
     * @return the value of risk_approvestrategyresult.mobileOnlineTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getMobileOnlineTime() {
        return mobileOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.mobileOnlineTime
     *
     * @param mobileOnlineTime the value for risk_approvestrategyresult.mobileOnlineTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setMobileOnlineTime(String mobileOnlineTime) {
        this.mobileOnlineTime = mobileOnlineTime == null ? null : mobileOnlineTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.loanBlackList
     *
     * @return the value of risk_approvestrategyresult.loanBlackList
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getLoanBlackList() {
        return loanBlackList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.loanBlackList
     *
     * @param loanBlackList the value for risk_approvestrategyresult.loanBlackList
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setLoanBlackList(String loanBlackList) {
        this.loanBlackList = loanBlackList == null ? null : loanBlackList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.remark
     *
     * @return the value of risk_approvestrategyresult.remark
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.remark
     *
     * @param remark the value for risk_approvestrategyresult.remark
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.createTime
     *
     * @return the value of risk_approvestrategyresult.createTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.createTime
     *
     * @param createTime the value for risk_approvestrategyresult.createTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.updateTime
     *
     * @return the value of risk_approvestrategyresult.updateTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.updateTime
     *
     * @param updateTime the value for risk_approvestrategyresult.updateTime
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.zrobotCredit
     *
     * @return the value of risk_approvestrategyresult.zrobotCredit
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getZrobotCredit() {
        return zrobotCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.zrobotCredit
     *
     * @param zrobotCredit the value for risk_approvestrategyresult.zrobotCredit
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setZrobotCredit(String zrobotCredit) {
        this.zrobotCredit = zrobotCredit == null ? null : zrobotCredit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.zrobotBlack
     *
     * @return the value of risk_approvestrategyresult.zrobotBlack
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getZrobotBlack() {
        return zrobotBlack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.zrobotBlack
     *
     * @param zrobotBlack the value for risk_approvestrategyresult.zrobotBlack
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setZrobotBlack(String zrobotBlack) {
        this.zrobotBlack = zrobotBlack == null ? null : zrobotBlack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.financalBehavior
     *
     * @return the value of risk_approvestrategyresult.financalBehavior
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getFinancalBehavior() {
        return financalBehavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.financalBehavior
     *
     * @param financalBehavior the value for risk_approvestrategyresult.financalBehavior
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setFinancalBehavior(String financalBehavior) {
        this.financalBehavior = financalBehavior == null ? null : financalBehavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approvestrategyresult.antiFraud
     *
     * @return the value of risk_approvestrategyresult.antiFraud
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public String getAntiFraud() {
        return antiFraud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approvestrategyresult.antiFraud
     *
     * @param antiFraud the value for risk_approvestrategyresult.antiFraud
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    public void setAntiFraud(String antiFraud) {
        this.antiFraud = antiFraud == null ? null : antiFraud.trim();
    }
}