package com.zdd.risk.bean;

import java.util.Date;

public class ApproveResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.id
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.userId
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.bizNo
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String bizNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.applyId
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.payIndex
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String payIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.approveResult
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String approveResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.approveCredit
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private Integer approveCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.approveAPR
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String approveAPR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.approveDPR
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String approveDPR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.minLoanTerm
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private Integer minLoanTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.maxLoanTerm
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private Integer maxLoanTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.refuseCode
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String refuseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.refuseReason
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String refuseReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.approveTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private Date approveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.createTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.remark
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveresult.updateTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.id
     *
     * @return the value of risk_approveresult.id
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.id
     *
     * @param id the value for risk_approveresult.id
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.userId
     *
     * @return the value of risk_approveresult.userId
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.userId
     *
     * @param userId the value for risk_approveresult.userId
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.bizNo
     *
     * @return the value of risk_approveresult.bizNo
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.bizNo
     *
     * @param bizNo the value for risk_approveresult.bizNo
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.applyId
     *
     * @return the value of risk_approveresult.applyId
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.applyId
     *
     * @param applyId the value for risk_approveresult.applyId
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.payIndex
     *
     * @return the value of risk_approveresult.payIndex
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getPayIndex() {
        return payIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.payIndex
     *
     * @param payIndex the value for risk_approveresult.payIndex
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setPayIndex(String payIndex) {
        this.payIndex = payIndex == null ? null : payIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.approveResult
     *
     * @return the value of risk_approveresult.approveResult
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getApproveResult() {
        return approveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.approveResult
     *
     * @param approveResult the value for risk_approveresult.approveResult
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setApproveResult(String approveResult) {
        this.approveResult = approveResult == null ? null : approveResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.approveCredit
     *
     * @return the value of risk_approveresult.approveCredit
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public Integer getApproveCredit() {
        return approveCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.approveCredit
     *
     * @param approveCredit the value for risk_approveresult.approveCredit
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setApproveCredit(Integer approveCredit) {
        this.approveCredit = approveCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.approveAPR
     *
     * @return the value of risk_approveresult.approveAPR
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getApproveAPR() {
        return approveAPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.approveAPR
     *
     * @param approveAPR the value for risk_approveresult.approveAPR
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setApproveAPR(String approveAPR) {
        this.approveAPR = approveAPR == null ? null : approveAPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.approveDPR
     *
     * @return the value of risk_approveresult.approveDPR
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getApproveDPR() {
        return approveDPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.approveDPR
     *
     * @param approveDPR the value for risk_approveresult.approveDPR
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setApproveDPR(String approveDPR) {
        this.approveDPR = approveDPR == null ? null : approveDPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.minLoanTerm
     *
     * @return the value of risk_approveresult.minLoanTerm
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public Integer getMinLoanTerm() {
        return minLoanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.minLoanTerm
     *
     * @param minLoanTerm the value for risk_approveresult.minLoanTerm
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setMinLoanTerm(Integer minLoanTerm) {
        this.minLoanTerm = minLoanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.maxLoanTerm
     *
     * @return the value of risk_approveresult.maxLoanTerm
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public Integer getMaxLoanTerm() {
        return maxLoanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.maxLoanTerm
     *
     * @param maxLoanTerm the value for risk_approveresult.maxLoanTerm
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setMaxLoanTerm(Integer maxLoanTerm) {
        this.maxLoanTerm = maxLoanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.refuseCode
     *
     * @return the value of risk_approveresult.refuseCode
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getRefuseCode() {
        return refuseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.refuseCode
     *
     * @param refuseCode the value for risk_approveresult.refuseCode
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setRefuseCode(String refuseCode) {
        this.refuseCode = refuseCode == null ? null : refuseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.refuseReason
     *
     * @return the value of risk_approveresult.refuseReason
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getRefuseReason() {
        return refuseReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.refuseReason
     *
     * @param refuseReason the value for risk_approveresult.refuseReason
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setRefuseReason(String refuseReason) {
        this.refuseReason = refuseReason == null ? null : refuseReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.approveTime
     *
     * @return the value of risk_approveresult.approveTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public Date getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.approveTime
     *
     * @param approveTime the value for risk_approveresult.approveTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.createTime
     *
     * @return the value of risk_approveresult.createTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.createTime
     *
     * @param createTime the value for risk_approveresult.createTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.remark
     *
     * @return the value of risk_approveresult.remark
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.remark
     *
     * @param remark the value for risk_approveresult.remark
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveresult.updateTime
     *
     * @return the value of risk_approveresult.updateTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveresult.updateTime
     *
     * @param updateTime the value for risk_approveresult.updateTime
     *
     * @mbg.generated Mon Nov 26 14:36:54 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}