package com.zdd.risk.bean;

import java.util.Date;

public class CertificationUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.id
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.userId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.mobile
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.realName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.nation
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.age
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.addressPermanent
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String addressPermanent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.idCardValidDate
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String idCardValidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.maritalStatus
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Integer maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.education
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Integer education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.institution
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String institution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.addressWork
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String addressWork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.addressHome
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String addressHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.payday
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String payday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.companyName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.companyPhone
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String companyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.sosContactName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String sosContactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.sosContactRelation
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Integer sosContactRelation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.sosContactPhone
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String sosContactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.sosContactName1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String sosContactName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.sosContactRelation1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Integer sosContactRelation1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.sosContactPhone1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String sosContactPhone1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.lastLoginIp
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.longitude
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.latitude
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.gpsAddress
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String gpsAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.regAppVersion
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String regAppVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.regFrom
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String regFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.regIp
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String regIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.bankCard
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String bankCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.bankMobile
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String bankMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.createTime
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.applyId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.updateTime
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.idCard
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.bankName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.productId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.regOs
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String regOs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certificationuserinfo.addressBook
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    private String addressBook;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.id
     *
     * @return the value of risk_certificationuserinfo.id
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.id
     *
     * @param id the value for risk_certificationuserinfo.id
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.userId
     *
     * @return the value of risk_certificationuserinfo.userId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.userId
     *
     * @param userId the value for risk_certificationuserinfo.userId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.mobile
     *
     * @return the value of risk_certificationuserinfo.mobile
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.mobile
     *
     * @param mobile the value for risk_certificationuserinfo.mobile
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.realName
     *
     * @return the value of risk_certificationuserinfo.realName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.realName
     *
     * @param realName the value for risk_certificationuserinfo.realName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.nation
     *
     * @return the value of risk_certificationuserinfo.nation
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.nation
     *
     * @param nation the value for risk_certificationuserinfo.nation
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.age
     *
     * @return the value of risk_certificationuserinfo.age
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.age
     *
     * @param age the value for risk_certificationuserinfo.age
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.addressPermanent
     *
     * @return the value of risk_certificationuserinfo.addressPermanent
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getAddressPermanent() {
        return addressPermanent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.addressPermanent
     *
     * @param addressPermanent the value for risk_certificationuserinfo.addressPermanent
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setAddressPermanent(String addressPermanent) {
        this.addressPermanent = addressPermanent == null ? null : addressPermanent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.idCardValidDate
     *
     * @return the value of risk_certificationuserinfo.idCardValidDate
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getIdCardValidDate() {
        return idCardValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.idCardValidDate
     *
     * @param idCardValidDate the value for risk_certificationuserinfo.idCardValidDate
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setIdCardValidDate(String idCardValidDate) {
        this.idCardValidDate = idCardValidDate == null ? null : idCardValidDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.maritalStatus
     *
     * @return the value of risk_certificationuserinfo.maritalStatus
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Integer getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.maritalStatus
     *
     * @param maritalStatus the value for risk_certificationuserinfo.maritalStatus
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setMaritalStatus(Integer maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.education
     *
     * @return the value of risk_certificationuserinfo.education
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.education
     *
     * @param education the value for risk_certificationuserinfo.education
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setEducation(Integer education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.institution
     *
     * @return the value of risk_certificationuserinfo.institution
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.institution
     *
     * @param institution the value for risk_certificationuserinfo.institution
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setInstitution(String institution) {
        this.institution = institution == null ? null : institution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.addressWork
     *
     * @return the value of risk_certificationuserinfo.addressWork
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getAddressWork() {
        return addressWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.addressWork
     *
     * @param addressWork the value for risk_certificationuserinfo.addressWork
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setAddressWork(String addressWork) {
        this.addressWork = addressWork == null ? null : addressWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.addressHome
     *
     * @return the value of risk_certificationuserinfo.addressHome
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getAddressHome() {
        return addressHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.addressHome
     *
     * @param addressHome the value for risk_certificationuserinfo.addressHome
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setAddressHome(String addressHome) {
        this.addressHome = addressHome == null ? null : addressHome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.payday
     *
     * @return the value of risk_certificationuserinfo.payday
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getPayday() {
        return payday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.payday
     *
     * @param payday the value for risk_certificationuserinfo.payday
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setPayday(String payday) {
        this.payday = payday == null ? null : payday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.companyName
     *
     * @return the value of risk_certificationuserinfo.companyName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.companyName
     *
     * @param companyName the value for risk_certificationuserinfo.companyName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.companyPhone
     *
     * @return the value of risk_certificationuserinfo.companyPhone
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.companyPhone
     *
     * @param companyPhone the value for risk_certificationuserinfo.companyPhone
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone == null ? null : companyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.sosContactName
     *
     * @return the value of risk_certificationuserinfo.sosContactName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getSosContactName() {
        return sosContactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.sosContactName
     *
     * @param sosContactName the value for risk_certificationuserinfo.sosContactName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setSosContactName(String sosContactName) {
        this.sosContactName = sosContactName == null ? null : sosContactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.sosContactRelation
     *
     * @return the value of risk_certificationuserinfo.sosContactRelation
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Integer getSosContactRelation() {
        return sosContactRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.sosContactRelation
     *
     * @param sosContactRelation the value for risk_certificationuserinfo.sosContactRelation
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setSosContactRelation(Integer sosContactRelation) {
        this.sosContactRelation = sosContactRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.sosContactPhone
     *
     * @return the value of risk_certificationuserinfo.sosContactPhone
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getSosContactPhone() {
        return sosContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.sosContactPhone
     *
     * @param sosContactPhone the value for risk_certificationuserinfo.sosContactPhone
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setSosContactPhone(String sosContactPhone) {
        this.sosContactPhone = sosContactPhone == null ? null : sosContactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.sosContactName1
     *
     * @return the value of risk_certificationuserinfo.sosContactName1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getSosContactName1() {
        return sosContactName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.sosContactName1
     *
     * @param sosContactName1 the value for risk_certificationuserinfo.sosContactName1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setSosContactName1(String sosContactName1) {
        this.sosContactName1 = sosContactName1 == null ? null : sosContactName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.sosContactRelation1
     *
     * @return the value of risk_certificationuserinfo.sosContactRelation1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Integer getSosContactRelation1() {
        return sosContactRelation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.sosContactRelation1
     *
     * @param sosContactRelation1 the value for risk_certificationuserinfo.sosContactRelation1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setSosContactRelation1(Integer sosContactRelation1) {
        this.sosContactRelation1 = sosContactRelation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.sosContactPhone1
     *
     * @return the value of risk_certificationuserinfo.sosContactPhone1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getSosContactPhone1() {
        return sosContactPhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.sosContactPhone1
     *
     * @param sosContactPhone1 the value for risk_certificationuserinfo.sosContactPhone1
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setSosContactPhone1(String sosContactPhone1) {
        this.sosContactPhone1 = sosContactPhone1 == null ? null : sosContactPhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.lastLoginIp
     *
     * @return the value of risk_certificationuserinfo.lastLoginIp
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.lastLoginIp
     *
     * @param lastLoginIp the value for risk_certificationuserinfo.lastLoginIp
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.longitude
     *
     * @return the value of risk_certificationuserinfo.longitude
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.longitude
     *
     * @param longitude the value for risk_certificationuserinfo.longitude
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.latitude
     *
     * @return the value of risk_certificationuserinfo.latitude
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.latitude
     *
     * @param latitude the value for risk_certificationuserinfo.latitude
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.gpsAddress
     *
     * @return the value of risk_certificationuserinfo.gpsAddress
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getGpsAddress() {
        return gpsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.gpsAddress
     *
     * @param gpsAddress the value for risk_certificationuserinfo.gpsAddress
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setGpsAddress(String gpsAddress) {
        this.gpsAddress = gpsAddress == null ? null : gpsAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.regAppVersion
     *
     * @return the value of risk_certificationuserinfo.regAppVersion
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getRegAppVersion() {
        return regAppVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.regAppVersion
     *
     * @param regAppVersion the value for risk_certificationuserinfo.regAppVersion
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setRegAppVersion(String regAppVersion) {
        this.regAppVersion = regAppVersion == null ? null : regAppVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.regFrom
     *
     * @return the value of risk_certificationuserinfo.regFrom
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getRegFrom() {
        return regFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.regFrom
     *
     * @param regFrom the value for risk_certificationuserinfo.regFrom
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setRegFrom(String regFrom) {
        this.regFrom = regFrom == null ? null : regFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.regIp
     *
     * @return the value of risk_certificationuserinfo.regIp
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getRegIp() {
        return regIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.regIp
     *
     * @param regIp the value for risk_certificationuserinfo.regIp
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setRegIp(String regIp) {
        this.regIp = regIp == null ? null : regIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.bankCard
     *
     * @return the value of risk_certificationuserinfo.bankCard
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.bankCard
     *
     * @param bankCard the value for risk_certificationuserinfo.bankCard
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.bankMobile
     *
     * @return the value of risk_certificationuserinfo.bankMobile
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getBankMobile() {
        return bankMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.bankMobile
     *
     * @param bankMobile the value for risk_certificationuserinfo.bankMobile
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setBankMobile(String bankMobile) {
        this.bankMobile = bankMobile == null ? null : bankMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.createTime
     *
     * @return the value of risk_certificationuserinfo.createTime
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.createTime
     *
     * @param createTime the value for risk_certificationuserinfo.createTime
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.applyId
     *
     * @return the value of risk_certificationuserinfo.applyId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.applyId
     *
     * @param applyId the value for risk_certificationuserinfo.applyId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.updateTime
     *
     * @return the value of risk_certificationuserinfo.updateTime
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.updateTime
     *
     * @param updateTime the value for risk_certificationuserinfo.updateTime
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.idCard
     *
     * @return the value of risk_certificationuserinfo.idCard
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.idCard
     *
     * @param idCard the value for risk_certificationuserinfo.idCard
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.bankName
     *
     * @return the value of risk_certificationuserinfo.bankName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.bankName
     *
     * @param bankName the value for risk_certificationuserinfo.bankName
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.productId
     *
     * @return the value of risk_certificationuserinfo.productId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.productId
     *
     * @param productId the value for risk_certificationuserinfo.productId
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.regOs
     *
     * @return the value of risk_certificationuserinfo.regOs
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getRegOs() {
        return regOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.regOs
     *
     * @param regOs the value for risk_certificationuserinfo.regOs
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setRegOs(String regOs) {
        this.regOs = regOs == null ? null : regOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certificationuserinfo.addressBook
     *
     * @return the value of risk_certificationuserinfo.addressBook
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public String getAddressBook() {
        return addressBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certificationuserinfo.addressBook
     *
     * @param addressBook the value for risk_certificationuserinfo.addressBook
     *
     * @mbg.generated Tue Nov 27 15:34:37 CST 2018
     */
    public void setAddressBook(String addressBook) {
        this.addressBook = addressBook == null ? null : addressBook.trim();
    }
}