package com.zdd.risk.dao;

import com.zdd.risk.bean.ApproveStrategyResult;
import com.zdd.risk.bean.ApproveStrategyResultExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IApproveStrategyResultDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    long countByExample(ApproveStrategyResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    int insert(ApproveStrategyResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    int insertSelective(ApproveStrategyResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    List<ApproveStrategyResult> selectByExampleWithBLOBs(ApproveStrategyResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    List<ApproveStrategyResult> selectByExample(ApproveStrategyResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ApproveStrategyResult record, @Param("example") ApproveStrategyResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ApproveStrategyResult record, @Param("example") ApproveStrategyResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approvestrategyresult
     *
     * @mbg.generated Thu Dec 06 10:22:54 CST 2018
     */
    int updateByExample(@Param("record") ApproveStrategyResult record, @Param("example") ApproveStrategyResultExample example);
}